- name: Config nginx.conf
  template:
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify:
    restart nginx

- name: Directory conf.d
  file:
    path: /etc/nginx/conf.d/
    state: directory
    owner: nginx
    mode: 0755

- name: Configure vhost wordpress
  template:
     src: "templates/wordpress.conf.j2"
     dest: "/etc/nginx/conf.d/wordpress.conf"
  notify:
     restart nginx