---
# tasks file for nginx_role
- name: Install nginx in CentOS 7
  import_tasks: nginx_centos.yml
  when: ansible_os_family == "RedHat"
  become: yes

- name: Configure vhost nginx
  import_tasks: config_vhost.yml
  become: yes

