---
#Install pré-requisites for wordpress
- name: Install pre-requisites for php 7
  yum:
     name: "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"
     #enablerepo: remi-php72
     state: present

- name: yum-clean-metadata
  command: yum clean metadata
  args: 
    warn: no

- name: Install pre-requisites for wordpress
  yum:
     name: [ 'epel-release','yum-utils','php','php-common','php-mysql','php-gd','php-xml','php-mbstring','php-mcrypt','php-fpm']
     state: present

- name: Start php-fpm
  service:
      name: php-fpm
      state: started
      enabled: yes


  
#Install Wordpress
- name: Extract Wordpress latest.tar.gz
  unarchive:
      src: http://wordpress.org/latest.tar.gz
      dest: /var/www/html
      owner: nginx
      mode: 0755
      remote_src: yes
  notify: restart nginx

- name: Configure vhost wordpress
  template:
     src: "templates/wp-config.php.j2"
     dest: "/var/www/html/wordpress/wp-config.php"
     owner: nginx
     mode: 0755
  notify:
     restart nginx

- name: Criar diretorio de log
  file:
     path: "/var/log/wordpress/"
     owner: nginx
     mode: 0755
     state: directory
  

- name: Criar o log access.log
  file:
     path: "/var/log/wordpress/access.log"
     owner: nginx
     mode: 0755
     state: touch

- name: Criar o log error.log
  file:
     path: "/var/log/wordpress/error.log"
     owner: nginx
     mode: 0755
     state: touch

   
    
      