---
# tasks file for mariadb_role
- include_vars:
   file: "{{ ansible_os_family }}.yml"


- include_tasks: install.yml
  vars:
    variable: value
  become: yes
- include_tasks: config.yml
  vars:
    variable: value
  become: yes

- include_tasks: database.yml
  vars:
    variable: value
  become: yes